name: CI with Allure Report
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Permissions nécessaires pour que l'Allure Action puisse commenter sur la PR
permissions:
  pull-requests: write
  checks: write
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout du code
      - name: Checkout
        uses: actions/checkout@v6

      # 2. Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: 'npm'

      # 3. Installation des dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Run tests (must use Allure reporter)
      - name: Run tests and generate report
        run: npx allure run -- npm run test

      # 5. Post summary to PR
      - name: Run Allure Action
        uses: allure-framework/allure-action@v0
        with:
          report-directory: "./allure-report"
          github-token: ${{ secrets.GITHUB_TOKEN }}
